name: tmc-cli-rust
title: TestMyCode CLI
base: core20
version: 1.1.0
issues: https://github.com/rage/tmc-cli-rust/issues
source-code: https://github.com/rage/tmc-cli-rust.git
website: https://tmc.mooc.fi/
summary: Client for TestMyCode.
description: Client for downloading, testing and submitting exercises through the TestMyCode system.
confinement: strict
license: Apache-2.0

plugs:
  home-folder-permissions:
    interface: personal-files
    read:
      - $HOME
    write:
      - $HOME

parts:
  tmc-cli-rust:
    plugin: nil
    source: . 
    override-pull: | 
      curl https://download.mooc.fi/tmc-cli-rust/tmc-cli-rust-x86_64-unknown-linux-gnu-v1.1.0 > tmc
      chmod +x tmc
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp tmc $SNAPCRAFT_PART_INSTALL/bin/
    build-packages:
      - curl
apps:
  tmc-cli-rust:
    command: bin/tmc
    plugs:
      - home-folder-permissions
